-- Disable RLS on all tables to allow full access
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.grounds DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.ground_facilities DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.facilities DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.games DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_slots DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.time_slots DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sports_areas DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.events DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sports_professionals DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.ground_inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.direct_sales DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.phone_registrations DISABLE ROW LEVEL SECURITY;